name: engg3130
channels:
  - vpython
  - conda-forge
dependencies:
  - python=3
  - jupyterlab==4.3.1
  - numpy
  - matplotlib
  - seaborn
  - networkx=2
  - sphinx
  - tqdm
  - future
  - pip
  - pip:
    - empiricaldist
    - jupyterlab-vpython==3.1.8
  - python-lsp-server
  - jupyterlab-lsp
  - vpython==7.6.5
